server:
  port: 9000   #使用ribbon本地集群的话，只改一下这个端口就行了，其它都一样

spring:
  application:
    name: user-service  #服务的别名（注册到注册中心的名称）

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka   #注册到这个注册中心
    register-with-eureka: true   #需要将我的服务注册到eureka
    fetch-registry: true   #作用：要不要去注册中心获取其他服务的地址
  instance:
    lease-renewal-interval-in-seconds: 1  #向Eureka服务端发起心跳的间隔时间，单位秒
    lease-expiration-duration-in-seconds: 2   #Eureka服务端在收到一次心跳之后等待的时间上限，超过则剔除，单位秒

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000